In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
os.chdir(r'C:\Users\Lenovo\Desktop\Diabetes_Classifier\notebooks')
os.chdir("..")
print(os.getcwd())

C:\Users\Lenovo\Desktop\Diabetes_Classifier

In [4]:
import pandas as pd
from src.data_investigation import *
df=pd.read_csv("data/raw/Diabetes Classification.csv")
print(df.shape)
df.head()

(5132, 11)

   Unnamed: 0  Age Gender  BMI  Chol   TG  HDL  LDL    Cr  BUN  Diagnosis
0           0   50      F   24   4.2  0.9  2.4  1.4  46.0  4.7          0
1           1   26      M   23   3.7  1.4  1.1  2.1  62.0  4.5          0
2           2   33      M   21   4.9  1.0  0.8  2.0  46.0  7.1          0
3           3   45      F   21   2.9  1.0  1.0  1.5  24.0  2.3          0
4           4   50      F   24   3.6  1.3  0.9  2.1  50.0  2.0          0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5132 entries, 0 to 5131
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5132 non-null   int64
 1   Age         5132 non-null   int64
 2   Gender      5132 non-null   str
 3   BMI         5132 non-null   int64
 4   Chol        5132 non-null   float64
 5   TG          5132 non-null   float64
 6   HDL         5132 non-null   float64
 7   LDL         5132 non-null   float64
 8   Cr          5132 non-null   float64
 9   BUN         5132 non-null   float64
 10  Diagnosis   5132 non-null   int64
dtypes: float64(6), int64(4), str(1)
memory usage: 441.2 KB

Out of 11 columns, no missing values and only 1 categorical value

In [6]:
df.describe()

,Unnamed: 0,Age,BMI,Chol,TG,HDL,LDL,Cr,BUN,Diagnosis
count,5132.000000,5132.000000,5132.000000,5132.000000,5132.000000,5132.000000,5132.000000,5132.000000,5132.000000,5132.000000
mean,2565.500000,48.950312,24.613406,4.866882,1.719328,1.593305,2.914121,71.144800,4.896969,0.388348
std,1481.625121,14.048794,4.277205,1.001052,1.327057,1.038849,0.945423,28.494394,1.689206,0.487422
min,0.000000,20.000000,15.000000,0.000000,0.000000,0.000000,0.300000,4.860753,0.500000,0.000000
25%,1282.750000,36.000000,22.000000,4.190000,0.910000,1.090000,2.290000,58.000000,3.900000,0.000000
50%,2565.500000,49.000000,24.000000,4.800000,1.380000,1.300000,2.790000,70.200000,4.720000,0.000000
75%,3848.250000,59.000000,27.000000,5.460000,2.100000,1.590000,3.400000,81.600000,5.600000,1.000000
max,5131.000000,93.000000,47.000000,11.650000,32.640000,9.900000,9.900000,800.000000,38.900000,1.000000

In [7]:
numerical,categorical=featureType(df)
cardinality(categorical,df)

<StringArray>
['F', 'M', 'f']
Length: 3, dtype: str
Gender
M    3256
F    1875
f       1
Name: count, dtype: int64

From the single categorical feature there are 3 unique values of which 'f' appears only once and most likely represents 'F'

In [8]:
target=df['Diagnosis']
print(target.value_counts(normalize=True)*100)

Diagnosis
0    61.165238
1    38.834762
Name: proportion, dtype: float64

Target is decently distributed at 62/38

In [9]:
df=df.drop(['Unnamed: 0'],axis=1)

In [10]:
df.duplicated().sum()

np.int64(0)

In [17]:
index=list()
for col in df.columns:
    if col=='Gender' or col=='Diagnosis':
        continue
    df[col].apply(lambda x:index.append(col) if x==0 else x)
print(set(index))

{'HDL', 'Chol', 'TG'}