In [30]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [31]:
import os
os.chdir(r'C:\Users\Lenovo\Desktop\Diabetes_Classifier\notebooks')
os.chdir("..")
print(os.getcwd())

C:\Users\Lenovo\Desktop\Diabetes_Classifier

In [32]:
from modeling.XGBoost import XGBoost
from modeling.RandomForest import RandomForest
from modeling.KNN import KNN
from modeling.MLP import MLP
from modeling.SVC import SVC
from modeling.Ensemble import LR
from src.data_feature_engineering import features
from src.data_preprocessing import scaling
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score,recall_score,precision_score,balanced_accuracy_score,roc_auc_score,accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [33]:
PATH="data/clean/clean2.csv"
df=pd.read_csv(PATH)
df.head()
df.columns = df.columns.str.strip()

In [34]:
df.head()

,age,bmi,chol,tg,hdl,ldl,cr,bun,diagnosis,anomaly_score,gender
0,50.0,24.0,4.2,0.9,1.366,1.4,46.0,4.7,0.0,0,0
1,26.0,23.0,3.7,1.4,1.100,2.1,62.0,4.5,0.0,0,1
2,33.0,21.0,4.9,1.0,0.800,2.0,46.0,7.1,0.0,0,1
3,45.0,21.0,2.9,1.0,1.000,1.5,24.0,2.3,0.0,2,0
4,50.0,24.0,3.6,1.3,0.900,2.1,50.0,2.0,0.0,0,0

In [35]:


y=df['diagnosis']
X=df.drop(['diagnosis'],axis=1)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train,X_test=features(X_train,X_test)
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)

In [36]:

xgb=XGBoost()
xgb_params={'n_estimators': 7800, 'max_depth': 13, 'learning_rate': 0.03585979413065538, 'gamma': 0.00025046646096832056, 'min_child_weight': 8, 'reg_alpha': 9.979812055651985, 'reg_lambda': 0.041477402642739976, 'subsample': 0.9999355054935987, 'colsample_bytree': 0.8896668801909641, 'tree_method': 'hist', 'n_jobs': -1}
xgb.set_params(xgb_params)
pd.set_option('display.max_rows',None)
# m=xgb.evaluation(X_train,y_train)
# m.out()
#Optuna
# params=xgb.hyperparameter_tuning(X,y,30)
# xgb.set_params(params)

In [37]:
rf=RandomForest()
rf_params={'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None, 'n_jobs': -1, 'random_state': 42}
rf.set_params(rf_params)
# m=rf.evaluation(X_train,y_train)
# m.out()
# rf_params=rf.hyperparameter_tuning(X_train,y_train,20)

In [38]:

pd.set_option('display.max_columns',None)
X_train.head(5)

,age,bmi,chol,tg,hdl,ldl,cr,bun,anomaly_score,lipids,Age_x_BMI,HDL_x_LDL,BMI/LDL,BMI/HDL+LDL,bun_x_cr,chol/ldl,cluster_labels,Cluster 0,Cluster 1,Cluster 2,Cluster 3,Cluster 4,Cluster 5,gender
0,36.0,20.0,4.87,0.79,1.58,2.98,54.1,3.68,0,0.530201,720.0,4.7084,6.711409,4.385965,199.088,1.634228,4,3.793370,3.601016,7.696364,17.719969,1.484730,2.730251,0
1,43.0,22.0,4.08,0.61,1.74,2.03,49.3,4.59,0,0.857143,946.0,3.5322,10.837438,5.835544,226.287,2.009852,4,3.254650,5.571425,5.560007,15.671746,1.856525,3.796267,0
2,25.0,20.0,4.60,1.00,1.33,2.63,80.0,4.25,0,0.505703,500.0,3.4979,7.604563,5.050505,340.000,1.749049,4,3.047396,4.147413,7.150937,17.217485,1.333657,2.476078,1
3,33.0,24.0,4.20,1.50,1.20,2.30,62.0,5.30,0,0.521739,792.0,2.7600,10.434783,6.857143,328.600,1.826087,0,1.540644,4.597134,5.843839,16.342171,1.732782,2.455300,0
4,72.0,21.0,5.33,1.55,1.20,2.94,65.0,3.56,0,0.408163,1512.0,3.5280,7.142857,5.072464,231.400,1.812925,5,2.945748,3.597536,6.986267,17.048253,2.434631,1.982158,0

In [39]:
X_train_scaled,X_test_scaled=scaling(X_train,X_test,'anomaly_score')
X_train_scaled.head()

,age,bmi,chol,tg,hdl,ldl,cr,bun,lipids,Age_x_BMI,HDL_x_LDL,BMI/LDL,BMI/HDL+LDL,bun_x_cr,chol/ldl,cluster_labels,Cluster 0,Cluster 1,Cluster 2,Cluster 3,Cluster 4,Cluster 5,gender_1,anomaly_score_1,anomaly_score_2
0,-0.926521,-1.159976,0.045798,-0.954857,0.950285,0.083596,-1.007459,-0.911456,0.169306,-1.141956,0.636170,-0.639131,-0.885076,-1.090399,-0.253493,0.512305,0.144223,-0.370808,0.407747,0.386458,-0.952801,-0.239769,0.0,0.0,0.0
1,-0.426895,-0.625566,-0.839675,-1.188123,1.477014,-0.959983,-1.309793,-0.145113,1.661038,-0.612563,-0.153091,0.355667,-0.163435,-0.879468,0.368128,0.512305,-0.144721,0.458613,-0.866563,-0.567228,-0.767942,0.280283,0.0,0.0,0.0
2,-1.711648,-1.159976,-0.256832,-0.682713,0.127270,-0.300880,0.623887,-0.431439,0.057529,-1.657295,-0.176107,-0.423789,-0.554249,0.002385,-0.063475,0.512305,-0.255882,-0.140808,0.082407,0.152493,-1.027916,-0.363766,1.0,0.0,0.0
3,-1.140646,-0.091156,-0.705173,-0.034752,-0.300698,-0.663387,-0.509867,0.452802,0.130695,-0.973300,-0.671258,0.258585,0.345146,-0.086022,0.064014,-1.439899,-1.064032,0.048496,-0.697261,-0.255067,-0.829468,-0.373903,0.0,0.0,0.0
4,1.642985,-0.892771,0.561391,0.030045,-0.300698,0.039656,-0.320908,-1.012512,-0.387516,0.713264,-0.155910,-0.535107,-0.543317,-0.839816,0.042233,1.000356,-0.310401,-0.372273,-0.015817,0.073696,-0.480502,-0.604723,0.0,0.0,0.0

In [40]:
mlp=MLP()
mlp_params={'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00017146311867992375, 'learning_rate_init': 0.004552010146185333, 'batch_size': 64, 'max_iter': 400, 'early_stopping': True, 'random_state': 42}

mlp.set_params(mlp_params)



# m=mlp.evaluation(X_train_scaled,y_train)
# m.out()
# params=mlp.hyperparameter_tuning(X_train_scaled,y_train,20)
# mlp.set_params(params)

In [41]:
svc=SVC()
# m=svc.evaluation(X_train_scaled,y_train)
# m.out()

In [42]:
knn=KNN()
knn_params={'n_neighbors': 28, 'weights': 'uniform', 'metric': 'minkowski', 'p': 2, 'algorithm': 'kd_tree', 'leaf_size': 12, 'n_jobs': -1}
knn.set_params(knn_params)

m=knn.evaluation(X_train_scaled,y_train)
m.out()
# parameters=knn.hyperparameter_tuning(X_train_scaled,y_train,20)

Accuracy: 0.8080389768574909
Precision: 0.7943676117835194
F1: 0.7279910714181186
Recall: 0.6719745222929936
Balanced Accuracy:0.7821411073003428
ROC-AUC: 0.8969660422869634

In [43]:
ensemble=[xgb,rf,mlp,svc,knn]
X_train_copy=X_train_scaled.copy()
X_test_copy=X_test_scaled.copy()
oof=pd.DataFrame()
oof_test=pd.DataFrame()
for model in ensemble:
    X_train_scaled[f'OOF_{type(model).__name__}'],X_test_scaled[f'OOF_{type(model).__name__}']=model.oof(X_train,y_train,X_test,type(model).__name__,10)

XGBoost fold 1/10 done
XGBoost fold 2/10 done
XGBoost fold 3/10 done
XGBoost fold 4/10 done
XGBoost fold 5/10 done
XGBoost fold 6/10 done
XGBoost fold 7/10 done
XGBoost fold 8/10 done
XGBoost fold 9/10 done
XGBoost fold 10/10 done
RandomForest fold 1/10 done
RandomForest fold 2/10 done
RandomForest fold 3/10 done
RandomForest fold 4/10 done
RandomForest fold 5/10 done
RandomForest fold 6/10 done
RandomForest fold 7/10 done
RandomForest fold 8/10 done
RandomForest fold 9/10 done
RandomForest fold 10/10 done
MLP fold 1/10 done
MLP fold 2/10 done
MLP fold 3/10 done
MLP fold 4/10 done
MLP fold 5/10 done
MLP fold 6/10 done
MLP fold 7/10 done
MLP fold 8/10 done
MLP fold 9/10 done
MLP fold 10/10 done
SVC fold 1/10 done
SVC fold 2/10 done
SVC fold 3/10 done
SVC fold 4/10 done
SVC fold 5/10 done
SVC fold 6/10 done
SVC fold 7/10 done
SVC fold 8/10 done
SVC fold 9/10 done
SVC fold 10/10 done
KNN fold 1/10 done
KNN fold 2/10 done
KNN fold 3/10 done
KNN fold 4/10 done
KNN fold 5/10 done
KNN fold 6/10 done
KNN fold 7/10 done
KNN fold 8/10 done
KNN fold 9/10 done
KNN fold 10/10 done

In [44]:

oof.tail(2)

Empty DataFrame
Columns: []
Index: []

In [45]:
meta_x_model=LR()
params={'penalty':'l2',
    'C':0.01,
    'solver':'lbfgs',
    'max_iter':5000,
    'class_weight':'balanced',   # or None
    'random_state':42,
    'n_jobs':-1}

meta_x_model.set_params(params)

In [46]:
# X_eval=pd.concat([X_train_scaled,X_test_scaled])
# y_eval=pd.concat([y_train,y_test])

In [47]:
def compare(base: dict, meta: dict):
    for key in base:
        diff = meta[key] - base[key]
        symbol = "↑" if diff > 0 else ("↓" if diff < 0 else "=")
        print(f"{key}: base={base[key]:.4f} meta={meta[key]:.4f} {symbol} ({diff:+.4f})")

In [48]:
# for model in ensemble:
#     print("=================================")
#     print(f"Model: {model}")
#     if model.__class__.__name__ in ["XGBoost", "RandomForest"]:
        
#         compare(model.evaluation(X,y,5).values(),meta_x_model.evaluation(X_eval,y_eval).values())
#     else:
#         compare(model.evaluation(X_eval,y_eval,5).values(),meta_x_model.evaluation(X_eval,y_eval).values())

In [49]:
meta_x_model.train(X_train_scaled,y_train)
lr_proba=meta_x_model.predict_proba(X_test_scaled)
preds=meta_x_model.predict(X_test_scaled)

In [50]:

def measure(y_pred: np.ndarray, y_proba: np.ndarray, y_real: np.ndarray) -> dict:
    metrics = {}
    metrics['accuracy'] = accuracy_score(y_real, y_pred)
    metrics['balanced']=balanced_accuracy_score(y_real,y_pred)
    metrics['precision'] = precision_score(y_real, y_pred)
    metrics['f1'] = f1_score(y_real, y_pred)
    metrics['recall'] = recall_score(y_real, y_pred)
    metrics['roc_auc'] = roc_auc_score(y_real, y_proba[:,1])
    return metrics

In [51]:
logistic_regression_metrics=measure(preds,lr_proba,y_test)
print(logistic_regression_metrics)

{'accuracy': 0.8179162609542356, 'balanced': 0.8154443191959044, 'precision': 0.7669683257918553, 'f1': 0.7838150289017342, 'recall': 0.8014184397163121, 'roc_auc': 0.9008168553222802}

In [52]:
for model in ensemble:
    if model.__class__.__name__ in ["XGBoost", "RandomForest"]:
        model.train(X_train,y_train)
        print(model.__class__.__name__)
    else:
        model.train(X_train_copy,y_train)

XGBoost
RandomForest

In [53]:
for model in ensemble:
    print(f'Model:{model}')
    if model.__class__.__name__ in ["XGBoost", "RandomForest"]:
        predictions=model.predict(X_test)
        proba=model.predict_proba(X_test)
        vals=measure(predictions,proba,y_test)
        compare(vals,logistic_regression_metrics)
    else:
        predictions=model.predict(X_test_copy)
        proba=model.predict_proba(X_test_copy)
        vals=measure(predictions,proba,y_test)
        compare(vals,logistic_regression_metrics)

Model:<modeling.XGBoost.XGBoost object at 0x000001C0571B7250>
accuracy: base=0.8150 meta=0.8179 ↑ (+0.0029)
balanced: base=0.8002 meta=0.8154 ↑ (+0.0152)
precision: base=0.8123 meta=0.7670 ↓ (-0.0454)
f1: base=0.7613 meta=0.7838 ↑ (+0.0225)
recall: base=0.7163 meta=0.8014 ↑ (+0.0851)
roc_auc: base=0.9061 meta=0.9008 ↓ (-0.0053)
Model:<modeling.RandomForest.RandomForest object at 0x000001C0571B6710>
accuracy: base=0.8189 meta=0.8179 ↓ (-0.0010)
balanced: base=0.8032 meta=0.8154 ↑ (+0.0123)
precision: base=0.8229 meta=0.7670 ↓ (-0.0559)
f1: base=0.7646 meta=0.7838 ↑ (+0.0193)
recall: base=0.7139 meta=0.8014 ↑ (+0.0875)
roc_auc: base=0.9076 meta=0.9008 ↓ (-0.0068)
Model:<modeling.MLP.MLP object at 0x000001C044DD9310>
accuracy: base=0.8101 meta=0.8179 ↑ (+0.0078)
balanced: base=0.8007 meta=0.8154 ↑ (+0.0148)
precision: base=0.7822 meta=0.7670 ↓ (-0.0152)
f1: base=0.7642 meta=0.7838 ↑ (+0.0196)
recall: base=0.7470 meta=0.8014 ↑ (+0.0544)
roc_auc: base=0.9027 meta=0.9008 ↓ (-0.0019)
Model:<modeling.SVC.SVC object at 0x000001C00284F380>
accuracy: base=0.8189 meta=0.8179 ↓ (-0.0010)
balanced: base=0.8025 meta=0.8154 ↑ (+0.0130)
precision: base=0.8264 meta=0.7670 ↓ (-0.0595)
f1: base=0.7634 meta=0.7838 ↑ (+0.0205)
recall: base=0.7092 meta=0.8014 ↑ (+0.0922)
roc_auc: base=0.8948 meta=0.9008 ↑ (+0.0060)
Model:<modeling.KNN.KNN object at 0x000001C044DD9F90>
accuracy: base=0.7965 meta=0.8179 ↑ (+0.0214)
balanced: base=0.7760 meta=0.8154 ↑ (+0.0395)
precision: base=0.8110 meta=0.7670 ↓ (-0.0441)
f1: base=0.7275 meta=0.7838 ↑ (+0.0563)
recall: base=0.6596 meta=0.8014 ↑ (+0.1418)
roc_auc: base=0.8931 meta=0.9008 ↑ (+0.0078)

In [54]:
X_train_scaled.iloc[:,-4:].corr()

                  OOF_RandomForest   OOF_MLP   OOF_SVC   OOF_KNN
OOF_RandomForest          1.000000  0.912504  0.844940  0.845743
OOF_MLP                   0.912504  1.000000  0.882586  0.862553
OOF_SVC                   0.844940  0.882586  1.000000  0.955352
OOF_KNN                   0.845743  0.862553  0.955352  1.000000

In [55]:
print(oof)

Empty DataFrame
Columns: []
Index: []

In [56]:
feature_cols=X_train_scaled.columns
meta_x_model.feature_importance(feature_cols)

             feature  coefficient
26  OOF_RandomForest     0.544720
25       OOF_XGBoost     0.514726
0                age     0.453026
9          Age_x_BMI     0.442870
5                ldl     0.284768
20         Cluster 4     0.282505
6                 cr    -0.237712
1                bmi     0.230607
29           OOF_KNN     0.180618
28           OOF_SVC     0.166396
3                 tg     0.165462
21         Cluster 5     0.152216
16         Cluster 0     0.151209
2               chol    -0.145943
27           OOF_MLP     0.131880
15    cluster_labels    -0.124042
4                hdl    -0.104874
13          bun_x_cr    -0.098265
7                bun     0.078466
14          chol/ldl    -0.065093
8             lipids    -0.063782
23   anomaly_score_1    -0.057861
18         Cluster 2     0.044482
24   anomaly_score_2     0.038463
10         HDL_x_LDL     0.038371
19         Cluster 3     0.034420
11           BMI/LDL     0.028202
17         Cluster 1    -0.016066
12       BMI/HDL+LDL    -0.015829
22          gender_1    -0.010934